package com.robonix.client.domain

import com.google.protobuf.TextFormat
import com.robonix.client.data.model.BodyComponentState
import com.robonix.client.data.model.BodyState
import com.robonix.client.data.model.HardwareSnapshot
import com.robonix.client.data.model.RobotComponent
import com.robonix.client.data.model.RobotDescription
import com.robonix.proto.vitalsstream.VitalsSnapshot
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Test
import java.io.File

/**
 * Golden + parity test for the vitals mapper on REAL robot deployment data.
 *
 * Fixtures were captured live from the soma backend (192.168.5.7) via the app's
 * log channel:
 *   - dog_soma.yaml   the served robot-description YAML (Jueying Lite3 body)
 *   - dog.urdf        the URDF served by soma/get_urdf (render mode = urdf)
 *   - dog_snapshot.txt  the first VitalsSnapshot frame (protobuf text)
 *
 * The expected doc in src/test/resources/dog.golden.json is the normalized
 * JSON projection of the mapper output for these inputs. It was generated by
 * this same test (`-Dupdate.golden=true`) and cross-checked against the web
 * mapper (`src/robonix_client/vitals_transport.py`) via tools/web_parity.py —
 * the web client is the parity reference for these values.
 */
class RobotVitalsMapperGoldenTest {

    private fun resource(name: String): String {
        val stream = checkNotNull(javaClass.getResourceAsStream("/$name")) {
            "missing test resource /$name"
        }
        return stream.bufferedReader().use { it.readText() }
    }

    private fun snapshotFromText(text: String): VitalsSnapshot {
        val builder = VitalsSnapshot.newBuilder()
        TextFormat.merge(text, builder)
        return builder.build()
    }

    @Test
    fun dogFixtureMatchesGolden() {
        val description = RobotVitalsMapper.normalizeRobotDescription(
            yamlText = resource("dog_soma.yaml"),
            urdfXml = resource("dog.urdf"),
            robotIdHint = "simplebot",
            urdfAssetBaseUrl = "https://robonix.local/assets/",
        )
        val snapshot = snapshotFromText(resource("dog_snapshot.txt"))
        val hardware = RobotVitalsMapper.snapshotToHardware(snapshot, description)

        // Readable smoke assertions (failures are legible even without the diff).
        assertEquals("urdf", description.renderMode)
        assertEquals("mobile_robot", description.family)
        assertEquals(
            listOf(
                "body", "body/base", "body/base/left_wheel", "body/base/right_wheel",
                "body/base/battery", "body/head_camera", "body/hokuyo_lidar",
            ),
            description.components.map { it.id },
        )
        assertNotNull("expected a power summary from the fixture snapshot", hardware.power)
        assertEquals(description.components.size.toLong(), hardware.componentHealth.size.toLong())
        hardware.componentHealth.forEach { row ->
            assertEquals("body=${row.componentId} health=${row.health}", "ok", row.health)
        }

        val golden = File(goldenPath())
        if (updateGolden()) {
            golden.writeText(canonicalJson(description, hardware).toString(2) + "\n")
        }
        val actual = canonicalJson(description, hardware).toString(2) + "\n"
        assertEquals(
            "Mapper output drifted from golden. Regenerate intentionally with " +
                "-Dupdate.golden=true after confirming web parity (tools/web_parity.py).",
            golden.readText(),
            actual,
        )
    }

    // ---- canonical JSON projection of the mapper output ----

    private fun canonicalJson(description: RobotDescription, hw: HardwareSnapshot): JSONObject {
        val out = JSONObject()
        val desc = JSONObject()
        desc.put("id", description.id)
        desc.put("displayName", description.displayName)
        desc.put("family", description.family)
        val dims = JSONObject()
        dims.put("lengthM", round2(description.dimensions.lengthM))
        dims.put("widthM", round2(description.dimensions.widthM))
        dims.put("heightM", round2(description.dimensions.heightM))
        desc.put("dimensions", dims)
        val comps = JSONArray()
        description.components.forEach { comps.put(componentJson(it)) }
        desc.put("components", comps)
        desc.put("renderMode", description.renderMode)
        desc.put("summary", description.summary)
        out.put("description", desc)

        val snap = JSONObject()
        hw.power?.let { power ->
            val p = JSONObject()
            p.put("socPercent", round2(power.socPercent))
            p.put("voltage", round2(power.voltage))
            p.put("charging", power.charging)
            p.put("remainingSeconds", power.remainingSeconds)
            snap.put("power", p)
        }
        val signals = JSONArray()
        hw.signals.forEach { signal ->
            val s = JSONObject()
            s.put("key", signal.key)
            s.put("health", signal.health)
            s.put("status", signal.status)
            s.put("observedValue", round2(signal.observedValue))
            s.put("referenceValue", round2(signal.referenceValue))
            s.put("visualState", signal.visualState)
            signals.put(s)
        }
        snap.put("signals", signals)
        val bodies = JSONArray()
        hw.bodies.forEach { body -> bodies.put(bodyJson(body)) }
        snap.put("bodies", bodies)
        val rows = JSONArray()
        hw.componentHealth.forEach { row ->
            val r = JSONObject()
            r.put("componentId", row.componentId)
            r.put("health", row.health)
            r.put("visualState", row.visualState)
            r.put("signalCount", row.signalCount)
            r.put("detail", row.detail)
            rows.put(r)
        }
        snap.put("componentHealth", rows)
        out.put("snapshot", snap)
        return out
    }

    private fun componentJson(c: RobotComponent): JSONObject {
        val o = JSONObject()
        o.put("id", c.id)
        o.put("localId", c.localId)
        o.put("parentId", c.parentId)
        o.put("label", c.label)
        o.put("type", c.type)
        o.put("model", c.model)
        o.put("urdfLink", c.urdfLink)
        o.put("urdfJoint", c.urdfJoint)
        val providers = JSONArray()
        c.providers.forEach { providers.put(it) }
        o.put("providers", providers)
        return o
    }

    private fun bodyJson(b: BodyState): JSONObject {
        val o = JSONObject()
        o.put("key", b.key)
        o.put("model", b.model)
        o.put("health", b.health)
        o.put("status", b.status)
        o.put("message", b.message)
        val comps = JSONArray()
        b.components.forEach { c -> comps.put(componentStateJson(c)) }
        o.put("components", comps)
        return o
    }

    private fun componentStateJson(c: BodyComponentState): JSONObject {
        val o = JSONObject()
        o.put("id", c.id)
        o.put("parentId", c.parentId)
        o.put("name", c.name)
        o.put("kind", c.kind)
        o.put("model", c.model)
        o.put("temperature", round2(c.temperature))
        o.put("errorCode", c.errorCode)
        o.put("enabled", c.enabled)
        return o
    }

    private fun round2(value: Float): Double =
        Math.round(value * 100.0) / 100.0

    private fun goldenPath(): String =
        System.getProperty("golden.dir") ?: "src/test/resources/dog.golden.json"

    private fun updateGolden(): Boolean =
        System.getProperty("update.golden") == "true" ||
            System.getenv("UPDATE_GOLDEN") == "1"
}
